spring:
  application:
    name:
      ZoraShop-MiniShopeeE-CommercePlatform
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/zorashop_db}
    username: ${DB_USERNAME:zorashop_user}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: on
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true

  flyway:
    enabled: true
    baseline-on-migrate: true
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION:86400000}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
