CREATE TABLE reviews (
                         id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         product_id          BIGINT NOT NULL UNIQUE,
                         average_star        DECIMAL(2, 1) NOT NULL DEFAULT 0.0,
                         count_review        BIGINT NOT NULL DEFAULT 0,
                         star_5              BIGINT NOT NULL DEFAULT 0,
                         star_4              BIGINT NOT NULL DEFAULT 0,
                         star_3              BIGINT NOT NULL DEFAULT 0,
                         star_2              BIGINT NOT NULL DEFAULT 0,
                         star_1              BIGINT NOT NULL DEFAULT 0,
                         review_have_comment BIGINT NOT NULL DEFAULT 0,
                         review_have_picture BIGINT NOT NULL DEFAULT 0,
                         CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE reviews_item (
                              id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              reviews_id    BIGINT NOT NULL,
                              user_id       BIGINT NOT NULL,
                              order_item_id BIGINT UNIQUE,
                              variant_id    BIGINT,
                              star          INT NOT NULL CHECK (star BETWEEN 1 AND 5),
                              comment       TEXT,
                              count_like    BIGINT NOT NULL DEFAULT 0,
                              is_anonymous  BOOLEAN NOT NULL DEFAULT FALSE,
                              reply_comment TEXT,
                              reply_date    TIMESTAMP,
                              create_date   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              CONSTRAINT fk_reviews_item_reviews FOREIGN KEY (reviews_id) REFERENCES reviews(id) ON DELETE CASCADE,
                              CONSTRAINT fk_reviews_item_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                              CONSTRAINT fk_reviews_item_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL,
                              CONSTRAINT fk_reviews_item_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE SET NULL
);

CREATE TABLE reviews_media (
                               id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               review_item_id BIGINT NOT NULL,
                               media_url      VARCHAR(500) NOT NULL,
                               media_type     VARCHAR(20) NOT NULL DEFAULT 'IMAGE',
                               CONSTRAINT fk_reviews_media_item FOREIGN KEY (review_item_id) REFERENCES reviews_item(id) ON DELETE CASCADE
);

CREATE INDEX idx_reviews_product_id ON reviews(product_id);
CREATE INDEX idx_reviews_item_reviews_date ON reviews_item(reviews_id, create_date DESC);
CREATE INDEX idx_reviews_item_reviews_star ON reviews_item(reviews_id, star);
