CREATE TABLE refresh_token(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    user_id BIGINT not null ,
    jti VARCHAR(36) unique not null ,
    is_revoked BOOLEAN NOT NULL DEFAULT False,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiration_date TIMESTAMP not null,
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) references users(id) ON DELETE CASCADE
);
CREATE INDEX idx_refresh_token_expiration_date ON refresh_token(expiration_date);
CREATE INDEX idx_refresh_token_user_id ON refresh_token(user_id)
