CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ariant_id BIGINT NOT NULL UNIQUE,
    quantity INTEGER NOT NULL DEFAULT 0,
    reserved INTEGER NOT NULL DEFAULT 0,
    available INTEGER GENERATED ALWAYS AS (quantity - reserved) STORED,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_inventory_variant
        FOREIGN KEY (variant_id)
            REFERENCES product_variant(id),
    CONSTRAINT chk_inventory_quantity
        CHECK (quantity >= 0),
    CONSTRAINT chk_inventory_reserved
        CHECK (reserved >= 0)
);