CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL UNIQUE,
    quantity INTEGER NOT NULL DEFAULT 0,
    reserved INTEGER NOT NULL DEFAULT 0,
    available INTEGER GENERATED ALWAYS AS (quantity - reserved) STORED,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_inventory_variant
        FOREIGN KEY (variant_id)
            REFERENCES product_variants(id),
    CONSTRAINT chk_inventory_quantity
        CHECK (quantity >= 0),
    CONSTRAINT chk_inventory_reserved
        CHECK (reserved >= 0)
);

CREATE TABLE inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL
        CHECK (type IN ('IN', 'OUT', 'RESERVED', 'RELEASED')),
    quantity_change INT NOT NULL,
    quantity_after INT NOT NULL,
    reason VARCHAR(255),
    reference_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_logs_inventory
        FOREIGN KEY (inventory_id)
            REFERENCES inventory(id)
);