CREATE TABLE cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT user_cart
        FOREIGN KEY (user_id)
            REFERENCES users(id)
);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    add_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cart_item
        FOREIGN KEY (cart_id)
            REFERENCES cart(id),
    CONSTRAINT item_variant
        FOREIGN KEY (variant_id)
            REFERENCES product_variants(id)
);